python ../scripts/discriminative_driver.py \
       --model mult \
       --mode train \
       --num_train_epochs 30 \
       --checkpoint_dir ./data/ckpt/Target_Topic2_nopretrain_meanmax_relu_0.1/ \
       --datasets Target Topic2 \
       --class_sizes 3 2 \
       --dataset_paths data/tf/merged/Target_Topic2/min_1_max_-1_vocab_-1_doc_-1/Target/ data/tf/merged/Target_Topic2/min_1_max_-1_vocab_-1_doc_-1/Topic2/ \
       --topics_path data/tf/merged/Target_Topic2/min_1_max_-1_vocab_-1_doc_-1/Target/data.json.gz data/tf/merged/Target_Topic2/min_1_max_-1_vocab_-1_doc_-1/Topic2/data.json.gz \
       --topic_field_name text \
       --encoder_config_file encoders.json \
       --architecture meanmax_relu_0.1_nopretrain \
       --shared_mlp_layers 1 \
       --shared_hidden_dims 100 \
       --private_mlp_layers 1 \
       --private_hidden_dims 100 \
       --alphas 0.5 0.5 \
       --optimizer rmsprop \
       --lr0 0.001 \
       --seed 42 \
       --summaries_dir ./data/summ/Target_Topic2_nopretrain/ \
       --log_file data/logs/Target_Topic2_nopretrain.log \
       --tuning_metric Acc \
       --metrics Acc Precision_Macro Recall_Macro F1_Macro
