python ../scripts/discriminative_driver.py \
       --model mult \
       --mode train \
       --num_train_epochs 30 \
       --vocab_size_file data/tf/single/SSTb/min_1_max_-1_vocab_-1/vocab_size.txt \
       --checkpoint_dir ./data/ckpt/paragram_nopretrain/ \
       --datasets SSTb \
       --dataset_paths data/tf/single/SSTb/min_1_max_-1_vocab_-1/ \
       --class_sizes 5 \
       --encoder_config_file encoders.json \
       --architecture paragram_nopretrain \
       --shared_mlp_layers 1 \
       --shared_hidden_dims 128 \
       --private_mlp_layers 1 \
       --private_hidden_dims 128 \
       --alphas 1 \
       --optimizer rmsprop \
       --lr0 0.0005 \
       --tuning_metric Acc \
       --topics_path data/json/GOV/data.json.gz data/json/LIF/data.json.gz data/json/BUS/data.json.gz data/json/LAW/data.json.gz data/json/HEA/data.json.gz data/json/MIL/data.json.gz \
       --seed 42 \
       --log_file paragram_nopretrain.log \
       --topic_field_name text
